### ISSUE TITLE
Multiple failures

### ISSUE THREAD

**Issue by JaggeV** [eyeonus/EDDBlink#3]
I pulled the latest version just a while ago and tried to run it. First I tried to run in directly after the previous fail, i.e. the 24h clean run from which I previously filed a bug, result was this:

python3 trade.py import -P "eddblink" -O skipvend
NOTE: Rebuilding cache file: this may take a few moments.
NOTE: Import complete: 0 items over 0 stations in 0 systems
NOTE: Regenerating .prices file.
Traceback (most recent call last):
  File "trade.py", line 104, in <module>
    main(sys.argv)
  File "trade.py", line 77, in main
    results = cmdenv.run(tdb)
  File "/home/jagge/trade2/commands/commandenv.py", line 81, in run
    return self._cmd.run(results, self, tdb)
  File "/home/jagge/trade2/commands/import_cmd.py", line 124, in run
    if not plugin.run():
  File "/home/jagge/trade2/plugins/eddblink_plug.py", line 761, in run
    cache.regeneratePricesFile(tdb, tdenv)
  File "/home/jagge/trade2/cache.py", line 1159, in regeneratePricesFile
    debug=tdenv.debug)
  File "/home/jagge/trade2/prices.py", line 62, in dumpPrices
    longestName = max(items.values(), key=lambda ent: len(ent[0]))
ValueError: max() arg is an empty sequence

Next I thought, fine, lets do things from scratch:
python3 trade.py import -P "eddblink" -O clean,skipvend 
Traceback (most recent call last):
  File "trade.py", line 104, in <module>
    main(sys.argv)
  File "trade.py", line 77, in main
    results = cmdenv.run(tdb)
  File "/home/jagge/trade2/commands/commandenv.py", line 81, in run
    return self._cmd.run(results, self, tdb)
  File "/home/jagge/trade2/commands/import_cmd.py", line 124, in run
    if not plugin.run():
  File "/home/jagge/trade2/plugins/eddblink_plug.py", line 692, in run
    tdb.load(maxSystemLinkLy = tdenv.maxSystemLinkLy)
  File "/home/jagge/trade2/tradedb.py", line 2028, in load
    self._loadAdded()
  File "/home/jagge/trade2/tradedb.py", line 766, in _loadAdded
    self.cur.execute(stmt)
sqlite3.OperationalError: no such table: Added

And now all -O clean runs will result in an error above

**Comment by JaggeV** [comment]
Was just about to send info on fix, but you beat me by 3 minutes :)

**Comment by eyeonus** [comment]
The first error was caused by you not fixing the problem from the previous version - your Item table was still empty.

Since I doubt you know how to fix that, you can't really be blamed for that.
Minimally, you would have had to run '-O item,force'.

The second error is an actual error.
